### ISSUE TITLE
Footer email address

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Sociology#10]
Change "sociology@temple.edu" to "soc@temple.edu"

**Comment by tu-chill** [comment]
sociology@temple.edu is a distribution list set up by our team. soc@temple.edu is owned by someone else. hopefully, someone who is affiliated with the sociology program.

We've set up standardized distribution lists for all programs. All programs should use our distribution lists. We can check to be sure that soc@temple.edu has been added to the distribution list.
