### ISSUE TITLE
Add NTT faculty members

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Sociology#12]
These NTT faculty members (names and titles below) should be added in-line with the current faculty members. Kim is working on getting us bios (though some are available on the current site) and CVs for all.

David Allen, Associate Professor of Teaching Instruction
Michael Altimore, Associate Professor of Teaching Instruction
Amanda Czerniawski, Associate Professor of Teaching Instruction
Ben Marcus, Associate Professor of Teaching Instruction
Geoff Moss, Associate Professor of Teaching Instruction
Donna Marie Peters, Associate Professor of Teaching Instruction
Mary Stricker, Associate Professor of Teaching Instruction
Ray Halnon, Assistant Professor of Teaching Instruction

**Comment by CVE82** [comment]
Added the NTT and pushed to dev
