### ISSUE TITLE
Placeholder not showing up for new faculty

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Sociology#13]
Hey hey the Temple T placeholder is not appearing for the NTT faculty i just entered.. Any guesses?

**Comment by tu-chill** [comment]
This that issue in Drupal views where the path is empty so we want to re-right the result with the path to the place holder I can get to this after lunch. Or feel free to fix it

**Comment by CVE82** [comment]
Roger that, I'm on it!

**Comment by tu-chill** [comment]
I'm going to be in each profile feed to update the file name. I'll check the "no results" value while I'm at it.

**Comment by CVE82** [comment]
Okay, sorry got sidetracked with Asian Studies. Do you want me to re-write the path/placeholder still?

**Comment by tu-chill** [comment]
view in drupal is correct. may need a travis rebuild to see.

**Comment by CVE82** [comment]
I did a Travis rebuild, still no luck.. =(

**Comment by tu-chill** [comment]
Drupal View fixed. for headshot path if empty use path to place holder
