### ISSUE TITLE
Sociology Content Updates

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Sociology#16]
The two pages of web updates are complete. The majority is spacing and spelling errors. 
Incident # INC000001096268
[Corrections and Edits to Sociology Page.docx](https://github.com/TULiberalArts/Sociology/files/890764/Corrections.and.Edits.to.Sociology.Page.docx)

**Comment by tu-chill** [comment]
One Drupal Issue remains 
Judith Levine: 1) Out of order. Should not be at the top of the page. Should be alphabetized under L. 2)
