### ISSUE TITLE
Events from Liberal Arts

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/Sociology#2]
more than one and up to 5 - show list

if one - display one

if none - display

https://liberalarts.temple.edu/events/sociology/rss
https://liberalarts.temple.edu/events/sociology/json
https://liberalarts.temple.edu/events/sociology/csv

**Comment by pixelyunicorn** [comment]
It's blank?

**Comment by tu-chill** [comment]
There maybe no data available. @TODO if no results send custom text.

Will need input from zach

C.Hill
Marketing Technology
College of Liberal Arts
Temple University

On Feb 8, 2017, at 3:46 PM, Victor Lourng <notifications@github.com<mailto:notifications@github.com>> wrote:


It's blank?

-

**Comment by tu-chill** [comment]
This has been added to TUTheme Issues
