### ISSUE TITLE
News feed

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Sociology#4]
Noticed that the news feed is pulling in media mentions instead of (or in addition to news stories). Not sure if this was on purpose -- can we replace the feed so it's news instead?

**Comment by tu-chill** [comment]
It was designed to pull in both media mentions and articles. We can change the functionality if you believe it is harmful

**Comment by zepstein** [comment]
That's okay with me, but it doesn't seem to be working properly. We've had sociology news stories that based on their date of publication should be included in the feed, but aren't appearing.

**Comment by zepstein** [comment]
This seems to be resolved now, pulling in both Media Mentions and Articles.
