### ISSUE TITLE
Fails to build after 10 min

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/Sociology#6]
Hi guys,

I made a change to Sociology this morning that still hasn’t appeared on the development site (it still says “published” and appears correctly in Prose.io though).

Any ideas about why this is? Does that mean something else is failing?

Thanks,
Zach

--
Zach Epstein
Director, Marketing and Communications
College of Liberal Arts
Temple University

**Comment by tu-chill** [comment]
Travis fails after 10 min while checking external links. Maybe too many links? I'm wandering if one of the links sends Travis into an infinite loop...

**Comment by lidopaglia** [comment]
I restarted the build. I'll check on it and make adjustments if we continue to run into stalled builds on this site.

**Comment by lidopaglia** [comment]
I believe this was caused by broken links. removed them in 5c801f92db564c6828149281828fa30739f80038 and e84dcb089db5b7a94d6a14811447e40cef5bdfe7. discovered this by running htmlproofer locally. not sure why one or both would have hung htmlproofer yet.
