### ISSUE TITLE
Hero image placement

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Sociology#9]
We just need to change the image so the top of it appears instead of the bottom (so we see people's faces instead of their hands and the table).

**Comment by tu-chill** [comment]
@ZMcGroarty We don't want to position the heroes individually. Is this image acceptable or should we try another image?

**Comment by ZMcGroarty** [comment]
I will make adjustments to the image Monday.



On Thu, Mar 9, 2017 at 4:12 PM -0500, "Christopher Hill" <notifications@github.com<mailto:notifications@github.com>> wrote:


@ZMcGroarty<https://github.com/ZMcGroarty> We don't want to position the heroes individually. Is this image acceptable or should we try another image?

**Comment by tu-chill** [comment]
Right Now You should be doing cup rap stuff!
On Mar 9, 2017, at 4:21 PM, Zachary McGroarty <notifications@github.com<mailto:notifications@github.com>> wrote:

I will make adjustments to the image Monday.



On Thu, Mar 9, 2017 at 4:12 PM -0500, "Christopher Hill" <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


@ZMcGroarty<https://github.com/ZMcGroarty> We don't want to position the heroes individually. Is this image acceptable or should we try another image?

**Comment by pixelyunicorn** [comment]
You are able to position each hero individually with custom CSS. By default all images are aligned to the center bottom, but I can change that.

**Comment by ZMcGroarty** [comment]
Lets try this one, adjusted lower.

![hero_sociology-min](https://cloud.githubusercontent.com/assets/15017242/24005510/9b2e24f8-0a3f-11e7-9c7f-9901c738d0a4.png)

**Comment by pixelyunicorn** [comment]
![image](https://cloud.githubusercontent.com/assets/607807/24015761/c402f1cc-0a5f-11e7-81d4-c5d4a2e46547.png)
Here's how it looks now:

**Comment by ZMcGroarty** [comment]
Perfect!

--
Zac McGroarty
Creative Director | Marketing and Communications
College of Liberal Arts
Temple University
—
1114 W. Berks St. | 832 Anderson Hall
Philadelphia, PA 19122
zachary.mcgroarty@temple.edu<mailto:zachary.mcgroarty@temple.edu>
liberalarts.temple.edu<http://liberalarts.temple.edu>





On Mar 16, 2017, at 3:46 PM, Victor Lourng <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://cloud.githubusercontent.com/assets/607807/24015761/c402f1cc-0a5f-11e7-81d4-c5d4a2e46547.png>
Here's how it looks now:

**Comment by tu-chill** [comment]
@victor thank you! Looks brilliant.
